steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/scriptrunner', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scriptrunner']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'scriptrunner', '--image', 'gcr.io/$PROJECT_ID/scriptrunner', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
